// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1___Ap1___Julio_Cesar_20180771.DAL;

namespace P1___Ap1___Julio_Cesar_20180771.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211006015901_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("P1___Ap1___Julio_Cesar_20180771.Entidades.Aportes", b =>
                {
                    b.Property<int>("AporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .HasColumnType("TEXT");

                    b.Property<string>("monto")
                        .HasColumnType("TEXT");

                    b.HasKey("AporteID");

                    b.ToTable("Aportes");
                });
#pragma warning restore 612, 618
        }
    }
}
